config/routes.rb
Rails.application.routes.draw do
  

  get 'testcases' => 'testcases#indexall'

  delete 'testcase/:id/destroy' => 'testcases#destroy'
  
  get 'assignments/:id/assign' => 'assignments#assign'
  
  post 'assignments/:id/assign' => 'assignments#items'

  root 'users#show'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :courses, :only => [:index]
  resources :admins, :only => [:show]
  resources :assignment_items, :only => [:show]
  resources :assignments do
    resources :testcases
  end
  get 'signup' => 'users#new'
  get 'assignments/:id/submissions' => 'assignments#view_all', as: :view_submissions
  get 'assignments/:id/submit' => 'assignment_items#submit', as: :submit
  post 'assignments/:id/submit' => 'assignment_items#create'
  get 'assignments/:id/trial' => 'assignment_items#trial', as: :trial
  post 'assignments/:id/trial' => 'assignment_items#test'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
   belongs_to :course
   has_one :course
   belongs_to :admin
   has_many :assignment_items, dependent: :destroy
   has_many :testcases
   
   validates :name, presence: true, length: {maximum:50}
   validates :content, presence: true
   
end
 

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy, :view_all]
  before_action :admin_user,     only: [:index, :new, :create, :edit, :update, :destroy, :view_all]
  
  def index
    if current_user
      @assignments = Assignment.all
    else
      redirect_to login_url
    end
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
    
    # Assigning to users here
    @all_users = User.where(isadmin: false)
    @assignment_item = AssignmentItem.new
  end
  
  def edit
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def assign
    @assignment = Assignment.find(params[:id])
    @users = User.where(isadmin: false)
  end
  
  def view_all
    @ai = @assignment.assignment_items
  end
  
  def items
  end
  
  def create
    @assignment = Assignment.new(assignment_params)
    @all_users = User.where(isadmin:false)
    @assignment_item = AssignmentItem.new

    respond_to do |format|
      if @assignment.save
        # Creating new assignment item here with the received id as parameter
        params[:users][:id].each do |uid|
          if !uid.empty?
            @ai = AssignmentItem.new(assignment_id:@assignment.id, user_id:uid)
            if @ai.save
              puts "saved for" + @ai.to_s
            else
              puts @ai.errors
            end
          end
        end
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully edited.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find_by(id:params[:id])
      if @assignment.nil?
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:name, :due, :points, :content, :submission)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
  def all_assignments
    @all_assignments ||= Assignment.all
  end
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <%= render 'shared/error_assignments' %>
  
  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.date_select :due %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :submission %><br>
    <%= f.text_area :submission %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignments/_newform.html.erb
<%= form_for(@assignment) do |f| %>
  <%= render 'shared/error_assignments' %>
  
  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.date_select :due %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :submission %><br>
    <%= f.text_area :submission %>
  </div>
  <!--User box here-->
  <%= fields_for(@assignment_item) do |ai| %>
    <div class="field">
      <%= ai.label "Assign to following students:" %><br>
      <%= collection_select(:users, :id, @all_users, :id, :name, {}, {:multiple => true}) %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignments/assign.html.erb
<p id="notice"><%= notice %></p>

<h1>Assigning to Users for <%= @assignment.name %></h1>

<%= form_tag do |f| %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.isadmin %></td>
        <td><%= link_to 'Show', AssignmentItem.find_by(assignment_id: @assignment.id, user_id: user.id) %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<br>

<%= link_to 'Back', @assignment %> | 
<%= link_to 'New User', new_user_path %>

app/views/assignments/edit.html.erb
<h1>Editing Assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<% provide(:title, "Listing Assignment") %>

<p id="notice"><%= notice %></p>

<h1>Listing Assignments</h1>
<div class="media">
  <div class="media-body">
    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Due</th>
          <th>Points</th>
          <th>Content</th>
          <th>Submission</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @assignments.each do |assignment| %>
          <tr>
            <td><%= assignment.name %></td>
            <td><%= assignment.due %></td>
            <td><%= assignment.points %></td>
            <td><%= assignment.content %></td>
            <td><%= assignment.submission %></td>
            <td><%= link_to 'Show', assignment, class: 'btn btn-xs btn-default' %></td>
            <td><%= link_to 'View Submissions', view_submissions_path(assignment), class: 'btn btn-xs btn-default' %></td>
            <td><%= link_to 'Edit', edit_assignment_path(assignment), class: 'btn btn-xs btn-success' %></td>
            <td><%= link_to 'Destroy', assignment, method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>  

<br>

<%= link_to 'New Assignment', new_assignment_path %>

app/views/assignments/new.html.erb
<% provide(:title, "New Assignment") %>
<h1>New Assignment</h1>

<%= render 'newform' %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @assignment.name %>
</p>

<p>
  <strong>Due:</strong>
  <%= @assignment.due %>
</p>

<p>
  <strong>Points:</strong>
  <%= @assignment.points %>
</p>

<p>
  <strong>Content:</strong>
  <%= @assignment.content %>
</p>

<p>
  <strong>Submission:</strong>
  <%= @assignment.submission %>
</p>

<% if isAdmin? %>
  <%= link_to 'Edit', edit_assignment_path(@assignment) %> |
  <%= link_to 'Assign', '/assignments/'+@assignment.id.to_s+'/assign' %> |
  <%= link_to 'Test Cases', assignment_testcases_path(@assignment) %> |
  <%= link_to 'Back', assignments_path %>
<% else %>
  <%= link_to 'Test Assignment', '/assignments/'+@assignment.id.to_s+'/trial', class: 'btn btn-success btn-xs' %>
  <%= link_to 'Submit Assignment', submit_path, class: 'btn btn-success btn-xs' %>
  <%= link_to 'View Submission', AssignmentItem.find_by(assignment_id: @assignment.id, user_id: current_user.id), class: 'btn btn-success btn-xs' %>
<% end %>

app/views/assignments/view_all.html.erb
<% provide(:title, "Assignment Submissions") %>

<p id="notice"><%= notice %></p>

<h1>Assignment <%= @assignment.name  %> submissions</h1>
<div class="media">
  <div class="media-body">
    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>Student's name</th>
          <th>Student's email</th>
          <th>Student's submission</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @ai.each do |ai| %>
          <tr>
            <td><%= ai.user.name %></td>
            <td><%= ai.user.email %></td>
            <td><%= link_to 'View Submission', ai, class: 'btn btn-xs btn-default' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div> 