config/routes.rb
Rails.application.routes.draw do
  

  get 'testcases' => 'testcases#indexall'

  delete 'testcase/:id/destroy' => 'testcases#destroy'
  
  get 'assignments/:id/assign' => 'assignments#assign'
  
  post 'assignments/:id/assign' => 'assignments#items'

  root 'users#show'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :courses, :only => [:index]
  resources :admins, :only => [:show]
  resources :assignment_items, :only => [:show]
  resources :assignments do
    resources :testcases
  end
  get 'signup' => 'users#new'
  get 'assignments/:id/submissions' => 'assignments#view_all', as: :view_submissions
  get 'assignments/:id/submit' => 'assignment_items#submit', as: :submit
  post 'assignments/:id/submit' => 'assignment_items#create'
  get 'assignments/:id/trial' => 'assignment_items#trial', as: :trial
  post 'assignments/:id/trial' => 'assignment_items#test'

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admins</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>