config/routes.rb
Rails.application.routes.draw do
  

  get 'testcases' => 'testcases#indexall'

  delete 'testcase/:id/destroy' => 'testcases#destroy'
  
  get 'assignments/:id/assign' => 'assignments#assign'
  
  post 'assignments/:id/assign' => 'assignments#items'

  root 'users#show'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :courses, :only => [:index]
  resources :admins, :only => [:show]
  resources :assignment_items, :only => [:show]
  resources :assignments do
    resources :testcases
  end
  get 'signup' => 'users#new'
  get 'assignments/:id/submissions' => 'assignments#view_all', as: :view_submissions
  get 'assignments/:id/submit' => 'assignment_items#submit', as: :submit
  post 'assignments/:id/submit' => 'assignment_items#create'
  get 'assignments/:id/trial' => 'assignment_items#trial', as: :trial
  post 'assignments/:id/trial' => 'assignment_items#test'

end

app/controllers/testcases_controller.rb
class TestcasesController < ApplicationController
  def show
    @assignment = Assignment.find_by(id:params[:assignment_id])
    @testcase = Testcase.find_by(id: params[:id])
  end

  def index
    if current_user
      @assignment = Assignment.find_by(id: params[:assignment_id])
      @testcases = Testcase.where(assignment: params[:assignment_id])
    else
      redirect_to login_url
    end
  end

  def indexall
    if current_user
      @testcases = Testcase.all
    else
      redirect_to login_url
    end
  end
  
  def new
    @assignment = Assignment.find_by(id:params[:assignment_id])
    @testcase = Testcase.new(assignment: @assignment)
  end
  
  def edit
    @assignment = Assignment.find_by(id:params[:assignment_id])
    @testcase = Testcase.find_by(id:params[:id])
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @testcase = Testcase.find_by(id: params[:id])
    aid = @testcase.assignment
    @testcase.destroy
    notice = ""
        
        items = AssignmentItem.where(assignment: aid)
        items.each do |item|
          tcs = Testcase.where(assignment: aid)
          testcases = { :num => 0, :tests => [] }
          tcs.each do |tc|
            testcases[:tests][testcases[:num]] = { :params => tc.parameters, :pat => tc.pattern }
            testcases[:num] += 1;
          end
          
          File.open("temp.cpp", "w+") do |f|
            f.write(item.submission)
          end
          success = system("g++ temp.cpp -o temp.out 2> temp.log")
          results = { :compiled => success, :output => File.read("temp.log"), :test_num => testcases[:num], :test_results => [] }
          
          if success
            i = 0
            while i < testcases[:num]
              system("./temp.out "+testcases[:tests][i][:params]+" 2>&1 > temp.txt")
              tout = File.read("temp.txt");
              match = /\A#{testcases[:tests][i][:pat]}\Z/.match( tout )
              results[:test_results][i] = { :test => testcases[:tests][i], :matches => !match.nil?, :output => tout }
              i += 1
            end
          end
          
          item.results = ActiveSupport::JSON.encode( results );
          if item.save()
            notice = notice + "item #" + item.id.to_s + " saved.\n"
          else
            notice = notice + "item #" + item.id.to_s + " not saved.\n"
          end
        end
        system("rm temp.cpp")
        system("rm temp.log")
        system("rm temp.out")
        system("rm temp.txt")
        
        respond_to do |format|
      format.html { redirect_to assignment_testcases_path(aid), notice: 'Test Case was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def create
    @assignment = Assignment.find_by(id: params[:assignment_id])
    @testcase = Testcase.new(assignment: @assignment, parameters: params[:testcase][:parameters], pattern: params[:testcase][:pattern])

    respond_to do |format|
      if @testcase.save
        notice = ""
        
        items = AssignmentItem.where(assignment: @assignment.id)
        items.each do |item|
          tcs = Testcase.where(assignment: @testcase.assignment)
          testcases = { :num => 0, :tests => [] }
          tcs.each do |tc|
            testcases[:tests][testcases[:num]] = { :params => tc.parameters, :pat => tc.pattern }
            testcases[:num] += 1;
          end
          
          File.open("temp.cpp", "w+") do |f|
            f.write(item.submission)
          end
          success = system("g++ temp.cpp -o temp.out 2> temp.log")
          results = { :compiled => success, :output => File.read("temp.log"), :test_num => testcases[:num], :test_results => [] }
          
          if success
            i = 0
            while i < testcases[:num]
              system("./temp.out "+testcases[:tests][i][:params]+" 2>&1 > temp.txt")
              tout = File.read("temp.txt");
              match = /\A#{testcases[:tests][i][:pat]}\Z/.match( tout )
              results[:test_results][i] = { :test => testcases[:tests][i], :matches => !match.nil?, :output => tout }
              i += 1
            end
          end
          
          item.results = ActiveSupport::JSON.encode( results );
          if item.save()
            notice = notice + "item #" + item.id.to_s + " saved.\n"
          else
            notice = notice + "item #" + item.id.to_s + " not saved.\n"
          end
        end
        system("rm temp.cpp")
        system("rm temp.log")
        system("rm temp.out")
        system("rm temp.txt")
        
        format.html { redirect_to [@assignment, @testcase], notice: notice + 'Test Case was successfully created.' }
        #format.html { redirect_to '/testcases' }
        format.json { render :show, status: :created, location: [@assignment, @testcase] }
      else
        format.html { render :new }
        format.json { render json: @testcase.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @assignment = Assignment.find_by(id: params[:assignment_id])
    @testcase = Testcase.find_by(id: params[:id])
    @testcase.assignment = @assignment
    @testcase.parameters = params[:testcase][:parameters]
    @testcase.pattern = params[:testcase][:pattern]
    
    respond_to do |format|
      if @testcase.save
        notice = ""
        
        items = AssignmentItem.where(assignment: @assignment.id)
        items.each do |item|
          tcs = Testcase.where(assignment: @testcase.assignment)
          testcases = { :num => 0, :tests => [] }
          tcs.each do |tc|
            testcases[:tests][testcases[:num]] = { :params => tc.parameters, :pat => tc.pattern }
            testcases[:num] += 1;
          end
          
          File.open("temp.cpp", "w+") do |f|
            f.write(item.submission)
          end
          success = system("g++ temp.cpp -o temp.out 2> temp.log")
          results = { :compiled => success, :output => File.read("temp.log"), :test_num => testcases[:num], :test_results => [] }
          
          if success
            i = 0
            while i < testcases[:num]
              system("./temp.out "+testcases[:tests][i][:params]+" 2>&1 > temp.txt")
              tout = File.read("temp.txt");
              match = /\A#{testcases[:tests][i][:pat]}\Z/.match( tout )
              results[:test_results][i] = { :test => testcases[:tests][i], :matches => !match.nil?, :output => tout }
              i += 1
            end
          end
          
          item.results = ActiveSupport::JSON.encode( results );
          if item.save()
            notice = notice + "item #" + item.id.to_s + " saved.\n"
          else
            notice = notice + "item #" + item.id.to_s + " not saved.\n"
          end
        end
        system("rm temp.cpp")
        system("rm temp.log")
        system("rm temp.out")
        system("rm temp.txt")
        
        format.html { redirect_to [@assignment, @testcase], notice: 'Test Case was successfully created.' }
        format.json { render :show, status: :created, location: @testcase }
      else
        format.html { render :new }
        format.json { render json: @testcase.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def testcase_params
      params.require(:testcase).permit(:assignment, :parameters, :pattern)
    end
end

app/helpers/testcases_helper.rb
module TestcasesHelper
end

app/views/testcases/_form.html.erb
<%= form_for [@assignment, @testcase] do |f| %>
  <% if @testcase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testcase.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @testcase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.hidden_field :assignment, value: @assignment.id %>
  <div class="field">
    <%= f.label :Parameters %><br>
    <%= f.text_field :parameters %>
  </div>
  <div class="field">
    <%= f.label :Pattern %><br>
    <%= f.text_area :pattern %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testcases/edit.html.erb
<h1>Editing Test Case</h1>

<%= render 'form' %>

<%= link_to 'Show', [@assignment,@testcase] %> |
<%= link_to 'Back', assignments_path %>

app/views/testcases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Test Cases</h1>

<table>
  <thead>
    <tr>
      <th>Parameters</th>
      <th>Pattern</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testcases.each do |testcase| %>
      <tr>
        <td><%= testcase.parameters %></td>
        <td><%= testcase.pattern %></td>
        <td><%= link_to 'Show', assignment_testcase_path(testcase.assignment,testcase) %></td>
        <td><%= link_to 'Edit', edit_assignment_testcase_path(@assignment,testcase) %></td>
        <td><%= link_to 'Destroy', [testcase.assignment, testcase], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', assignment_path(@assignment) %> |
<%= link_to 'New Test Case', new_assignment_testcase_path(@assignment) %>

app/views/testcases/indexall.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Test Cases</h1>

<table>
  <thead>
    <tr>
      <th>Parameters</th>
      <th>Pattern</th>
      <th>Assignment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testcases.each do |testcase| %>
      <tr>
        <td><%= testcase.parameters %></td>
        <td><%= testcase.pattern %></td>
        <% if testcase.assignment.nil? %>
          <td></td>
          <td>Show</td>
          <td>Edit</td>
          <td><%= link_to 'Destroy', 'testcase/'+testcase.id.to_s+'/destroy', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td><%= testcase.assignment.name %></td>
          <td><%= link_to 'Show', assignment_testcase_path(testcase.assignment,testcase) %></td>
          <td><%= link_to 'Edit', edit_assignment_testcase_path(testcase.assignment,testcase) %></td>
          <td><%= link_to 'Destroy', [testcase.assignment, testcase], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/testcases/new.html.erb
<h1>New Test Case</h1>

<%= render 'form' %>

<%= link_to 'Back', assignment_path(@assignment) %>

app/views/testcases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parameters:</strong>
  <%= @testcase.parameters %>
</p>

<p>
  <strong>Pattern:</strong>
  <%= @testcase.pattern %>
</p>

<%= link_to 'Edit', edit_assignment_testcase_path(@assignment,@testcase) %> |
<%= link_to 'Back', assignment_testcases_path(@assignment) %>