config/routes.rb
Rails.application.routes.draw do
  

  get 'testcases' => 'testcases#indexall'

  delete 'testcase/:id/destroy' => 'testcases#destroy'
  
  get 'assignments/:id/assign' => 'assignments#assign'
  
  post 'assignments/:id/assign' => 'assignments#items'

  root 'users#show'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :courses, :only => [:index]
  resources :admins, :only => [:show]
  resources :assignment_items, :only => [:show]
  resources :assignments do
    resources :testcases
  end
  get 'signup' => 'users#new'
  get 'assignments/:id/submissions' => 'assignments#view_all', as: :view_submissions
  get 'assignments/:id/submit' => 'assignment_items#submit', as: :submit
  post 'assignments/:id/submit' => 'assignment_items#create'
  get 'assignments/:id/trial' => 'assignment_items#trial', as: :trial
  post 'assignments/:id/trial' => 'assignment_items#test'

end

app/views/layouts/_admin.html.erb
<div class="col-lg-12">
  <h3>Listing Assignments</h3>
  <% if all_assignments.any? %>
    <%= render 'layouts/assignments' %>
  <% end %>
</div>

app/views/layouts/_assignment_items.html.erb
<div class="media">
  <div class="media-body">
    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>New Assignments (<%= @user_assignments.count %>)</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @user_assignments.each do |a| %>
          <tr>
            <% if a.assignment.name %>
              <td><%= a.assignment.name %></td>
            <% else %>
              <td>Assignment <%= a.id %>: </td>
            <% end %>
            <td>
              <%= link_to 'View Assignment', a.assignment, class: 'btn btn-xs btn-default' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_assignments.html.erb
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Assignment Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% all_assignments.each do |a| %>
          <tr>
            <% if a.name %>
              <td>Assignment <%= a.id %> <%= a.name %>:</td>
            <% else %>
              <td>Assignment <%= a.id %>: </td>
            <% end %>
            <td>
              <%= link_to 'View Submissions', a %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'Assignments Listing', assignments_path %> | 
<%= link_to 'Test Case Listing', '/testcases' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.fgcu.edu">Auto Grader II for C++ Assignments</a>
    by <a href="http://itech.fgcu.edu/faculty/zalewski/CEN4065/CEN4065-ListOfProjects2014.pdf">Team 6 - Rabeet Fatmi, Lloyd Gibson, Brent Oliver</a>
    for <a href="http://satnet.fgcu.edu/~munnerley/instructor_site/course10.html">CEN-4065 Software Architecture</a> 
    by <a href="http://satnet.fgcu.edu/~munnerley/instructor_site/index.html">Prof. Zalewski</a>
  </small>
  <nav>
    <ul>
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
  <div class="container-fluid">
    <%= link_to "Auto Grader II", root_path, id: "logo" %>
    <nav>
      <ul class="nav nav-tabs">
        <li><%= link_to current_user.name, current_user %></li>
        <% if isAdmin? %>
          <li><%= link_to "Users", users_path %></li>
        <% end %>
        <li><%= link_to "Courses",   courses_path %></li>
        <li><%= link_to "Help",   '#' %></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_user.html.erb
<div class="col-lg-12">
  <% if @user.assignment_items.any? %>
    <%= render 'layouts/assignment_items' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  <% if logged_in? %>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      <%= render 'layouts/footer' %>
    </div>
  <% else %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      <%= render 'layouts/footer' %>
    </div>
  <% end %>
  </body>
</html>